spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.79:3306/fyerp?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: yfbdb123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      format_sql: true
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.79
    port: 6379
    password: yfb123
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: my-es
      repositories:
        enabled: true

#  mvc:
#    view:
#      suffix: .html
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
logging:
  level:
    org:
      springframework:
        security: info
debug: false




