spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/semantic?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: yfbdb123
server:
  port: 8080
