spring:
#  profiles:
#    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.79:3306/fyerp?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
#    url: jdbc:mysql://localhost:3306/fyerp?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: yfbdb123
#    password: SDysjdsr1225
##设置最大上传大小为10Mb
#  http:
#    multipart:
#      max-file-size: 10Mb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.79
#    host: localhost
    port: 6379
    password: yfb123
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: my-es
      repositories:
        enabled: true
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
#  mvc:
#    view:
#      suffix: .html
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
logging:
  level: debug
#    org:
#      springframework:
#        security: info
debug: true

#文件上传路径
file:
  path: /Users/xuda/Downloads/
  name: xxx.docx













